Fix redirect on Listing(Archive) for texas-auction
yshalenyk/openprocurement.auction.js pull request #25
Opened 2018-11-05 11:08 UTC by vasyldanyliv

2018-11-05 11:13 UTC, oleksiyVeretiuk approved these changes

2018-11-05 11:33 UTC, oleksiyVeretiuk requested changes

2018-11-05 11:33 UTC, oleksiyVeretiuk commented on templates/archive.html
> +                  ng-show="(auction.doc.procurementMethodType) === 'texas'">
Винести в функцію, яка повертає правильне посилання в залежності від auction_type-a

2018-11-05 16:12 UTC, Scandie approved these changes

2018-11-05 16:13 UTC, Scandie requested changes

2018-11-05 16:13 UTC, Scandie commented on src/app/controllers/ArchiveCtl.js
> +  function(AuctionConfig,$scope, $http, $location) {
@vasyldanyliv, поверни пробіл :upside_down_face:

2018-11-06 10:27 UTC, leits approved these changes

2018-11-06 10:52 UTC, merged